"""sprint retrospective and comment edited_at

Revision ID: 056d83de5b21
Revises: 702bfbdb79d4
Create Date: 2026-07-27 15:44:46.377532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056d83de5b21'
down_revision = '702bfbdb79d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retro_good', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retro_bad', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retro_learned', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_column('retro_learned')
        batch_op.drop_column('retro_bad')
        batch_op.drop_column('retro_good')
        batch_op.drop_column('closed_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
