"""add epic roadmap dates

Revision ID: 702bfbdb79d4
Revises: f9628a1ed8ac
Create Date: 2026-07-21 14:31:05.942138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702bfbdb79d4'
down_revision = 'f9628a1ed8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
