"""idea task fields and attachments

Revision ID: 76443bd8950a
Revises: fea3d2ae883b
Create Date: 2026-08-05 13:24:26.033587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76443bd8950a'
down_revision = 'fea3d2ae883b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idea_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'])

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key(None, 'components', ['component_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assignee_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('component_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('team_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('priority')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idea_id')

    # ### end Alembic commands ###
