"""add issue priority

Revision ID: f9628a1ed8ac
Revises: e0ebe8c3a38f
Create Date: 2026-07-16 17:27:24.291943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9628a1ed8ac'
down_revision = 'e0ebe8c3a38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
