"""ideas

Revision ID: fea3d2ae883b
Revises: 6ab72721e768
Create Date: 2026-08-05 13:11:18.259096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea3d2ae883b'
down_revision = '6ab72721e768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['idea_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_idea_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ideas', ['source_idea_id'], ['id'])

    # ### end Alembic commands ###

    # Стартовые статусы идей
    idea_statuses = sa.table('idea_statuses',
                             sa.column('name', sa.String),
                             sa.column('position', sa.Integer))
    op.bulk_insert(idea_statuses, [
        {'name': 'Новая', 'position': 1},
        {'name': 'На обсуждении', 'position': 2},
        {'name': 'Одобрена', 'position': 3},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_idea_id')

    op.drop_table('idea_comments')
    op.drop_table('ideas')
    op.drop_table('idea_statuses')
    # ### end Alembic commands ###
